# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    commit-message:
      prefix: 'chore(dependabot): '
    target-branch: 'develop'
    # Every weekday
    schedule:
      interval: 'daily'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: '/'
    commit-message:
      prefix: 'chore(dependabot): '
    target-branch: 'develop'
    # Every weekday
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    commit-message:
      prefix: 'chore(dependabot): '
    target-branch: 'develop'
    # Every weekday
    schedule:
      interval: 'daily'
