services:
  redis:
    image: docker.io/redis:7-alpine
    restart: always
    container_name: verbacap-redis

  init-container:
    image: alpine:3.19
    command: chown -R 1000:1000 /persist /home/app/staticfiles
    volumes:
      - ./example/web:/persist
      - ./example/web-static:/home/app/staticfiles

  web:
    image: ghcr.io/mirio/verbacap:v1.5.0
    restart: always
    container_name: verbacap-web
    command: "run"
    ports:
      - 8080:8080
    depends_on:
      - redis
      - init-container
    environment:
      DATABASE_URL: "postgres://POSTGRES_USERNAME:POSTGRES_PASSWORD@POSTGRES_HOSTNAME:5432/postgres"
      DJANGO_SECRET_KEY: "CHANGEME_SECRET"
      DJANGO_DEBUG: "False"
      CELERY_BROKER_URL: "redis://verbacap-redis:6379/0"
      PERSIST_AUDIO_ROOTDIR: "/persist"
    volumes:
      - CHANGEME_PERSIST_PATH:/persist

  celery:
    image: ghcr.io/mirio/verbacap:v1.5.0
    restart: always
    container_name: verbacap-celery
    command: "celery"
    depends_on:
      - web
    environment:
      DATABASE_URL: "postgres://POSTGRES_USERNAME:POSTGRES_PASSWORD@POSTGRES_HOSTNAME:5432/postgres"
      DJANGO_SECRET_KEY: "CHANGEME_SECRET"
      DJANGO_DEBUG: "False"
      CELERY_BROKER_URL: "redis://verbacap-redis:6379/0"
      PERSIST_AUDIO_ROOTDIR: "/persist"
    volumes:
      - CHANGEME_PERSIST_PATH:/persist
