# Generated by Django 4.2.4 on 2023-08-08 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(help_text="Name of this datasource")),
                ("target", models.CharField(help_text="Target url/string based by the provider type")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("name", models.CharField(help_text="Provider name", unique=True)),
                ("icon", models.CharField(help_text="Font Awesome icon, insert full html")),
                ("color", models.CharField(default="#fff", help_text="HexColor to apply on the icon")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("episode_id", models.CharField(help_text="Episode ID (i.e Youtube ID)", unique=True)),
                ("name", models.CharField(help_text="Episode Name")),
                ("episode_date", models.DateField()),
                ("target", models.CharField(help_text="Episode target url/string based by Provider")),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_downloaded", models.BooleanField(default=False)),
                (
                    "datasource",
                    models.ForeignKey(
                        help_text="Datasource to use",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="provider",
            field=models.ForeignKey(
                help_text="Provider to use", on_delete=django.db.models.deletion.CASCADE, to="core.provider"
            ),
        ),
    ]
