# Generated by Django 4.2.4 on 2023-08-09 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("order_num", models.SmallIntegerField()),
                ("episode", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.episode")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
