# Generated by Django 4.2.4 on 2023-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_playlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="shortname",
            field=models.CharField(default="000", help_text="Prefix for the audio files"),
        ),
    ]
