# Generated by Django 4.2.7 on 2023-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="name",
            field=models.CharField(help_text="Settings Name", unique=True),
        ),
    ]
