# Generated by Django 4.2.7 on 2023-12-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_settings_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="current_time",
            field=models.IntegerField(default=0),
        ),
    ]
