# Generated by Django 4.2.7 on 2023-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_episode_current_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="current_time",
            field=models.IntegerField(default=0, help_text="Current time (for resume function)"),
        ),
    ]
