name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a latest changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest

      - name: Push the changelog into release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ steps.git-cliff.outputs.content }}

      - name: Push new changelog
        run: |
          git checkout develop
          echo '${{ steps.git-cliff.outputs.content }}' > CHANGELOG.md
          git config --global user.name "Mirio"
          git config --global user.email "1211529+Mirio@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Adding full changelog"
          git push
